url: "https://michalruprecht.com"
baseurl: ""

title: Michal Ruprecht

description: Michal Ruprecht is a medical student and health journalist covering mental health for NPR. His work has appeared in NPR, CNN, ABC News and MedPage Today. His reporting has been supported by The Carter Center, Pulitzer Center, Kresge Foundation, Association of Health Care Journalists, Association of American Medical Colleges, American Academy of Pediatrics and Stanford Center for Innovation in Global Health.

name: Michal T. Ruprecht

markdown: kramdown

author:
  name: Michal T. Ruprecht

url-pretty: "michalruprecht.com"

gtag: "'config', 'UA-141229929-1'"
google_analytics: "UA-141229929-1"

# Make sure Jekyll looks in your _layouts folder
layouts_dir: _layouts

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - PUBLISHING.md
  - Vagrantfile
  - node_modules
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
